# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt   


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:

        chain_provider:
            chain:
                providers: [in_memory, db_provider]

        db_provider:
                    entity:
                        class: AppBundle:User
                        property: username


        my_ldap_users:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: 'ou=Magyp Usuarios, dc=MAGYP, dc=AR'
                search_dn: '(sAMAccountName={username})'
                search_password: 'password'
                default_roles: ROLE_USER
                uid_key: 'uid'
                filter: '(&({uid_key}={username})(objectclass=person)(ou=Users))'

        in_memory:
            memory:
                users:

                    # php bin/console security:encode-password
                    ryan:
                        password: $2y$13$WSDdkOhxcCYhILc/G.HlBOmHtHfXWJ059HwJWPJ9FuYjzTcNVsIzu
                        roles: 'ROLE_USER'
                    admins:
                        password: $2y$13$WSDdkOhxcCYhILc/G.HlBOmHtHfXWJ059HwJWPJ9FuYjzTcNVsIzu
                        roles: 'ROLE_ADMIN'
                    pepe:
                        password: $2y$13$MZjGrgEHjDVtR21HKlmPMO4.XMW7tNF6xwIyoFCwHUR/2VhSdSfGW
                        roles: 'ROLE_SUPER_ADMIN'            

        

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:

            
            #The LDAP PHP extension is not enabled.
            form_login_ldap:
            #http_basic_ldap:
                login_path: login
                check_path: login
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'MAGYP\{username}'
            logout:
                path: /logout
                target: /santi    
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            #https://symfony.com/doc/current/security/form_login.html
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

                default_target_path: login
                always_use_default_target_path: true

                
            logout:
                path: /logout
                target: /santi    

        

        secured_area:
            # ...
            pattern: ^/
            provider: db_provider
            anonymous: ~
            http_basic:
                provider: in_memory
                      


    
    access_control:
        - {path: ^/^ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/login , roles: [IS_AUTHENTICATED_ANONYMOUSLY ,IS_AUTHENTICATED_FULLY] }
        - {path: ^/Admin , roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/tiosand, roles: ROLE_ADMIN }
        - { path: ^/admins, roles:   [ ROLE_ADMIN , IS_AUTHENTICATED_FULLY]}